name: cure_app
description: "A new Flutter project for Cure app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0' # هذا النطاق يسمح باستخدام Dart 3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6 # تم إضافة هذه الحزمة
  firebase_storage: ^12.4.6

  # إدارة الحالة
  provider: ^6.1.2

  # أدوات واجهة المستخدم
  flutter_rating_bar: ^4.0.0+1 # تم إضافة هذه الحزمة
  image_picker: ^1.1.0 # تم إضافة هذه الحزمة

  # أيقونات
  cupertino_icons: ^1.0.8

  # التنسيقات (مثل DateFormat)
  intl: ^0.20.2 # تم تحديث إصدارها

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # تم تحديث إصدارها

flutter:
  uses-material-design: true