// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz6d1z4BnINppGC6_5OsxwL570vWSMdbU',
    appId: '1:997897806633:web:3a1a01e9d1082bc59acd38',
    messagingSenderId: '997897806633',
    projectId: 'cure-app-ddfd9',
    authDomain: 'cure-app-ddfd9.firebaseapp.com',
    storageBucket: 'cure-app-ddfd9.firebasestorage.app',
    measurementId: 'G-36LW8FDP2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYWd5v-do4DNmovzppyHnzPM71JPr0bU',
    appId: '1:997897806633:android:d2a8ef602ceb7aff9acd38',
    messagingSenderId: '997897806633',
    projectId: 'cure-app-ddfd9',
    storageBucket: 'cure-app-ddfd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2OMp-svNRz0U0eZWyapPEREcftCjgkU',
    appId: '1:997897806633:ios:b853206d716bc4b59acd38',
    messagingSenderId: '997897806633',
    projectId: 'cure-app-ddfd9',
    storageBucket: 'cure-app-ddfd9.firebasestorage.app',
    androidClientId:
        '997897806633-cv758fcn80ijang5198d1qpv83m6bh67.apps.googleusercontent.com',
    iosClientId:
        '997897806633-5ni700nv2jmak77tmsprsshft6kvn0me.apps.googleusercontent.com',
    iosBundleId: 'com.example.cureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI2OMp-svNRz0U0eZWyapPEREcftCjgkU',
    appId: '1:997897806633:ios:b853206d716bc4b59acd38',
    messagingSenderId: '997897806633',
    projectId: 'cure-app-ddfd9',
    storageBucket: 'cure-app-ddfd9.firebasestorage.app',
    androidClientId:
        '997897806633-cv758fcn80ijang5198d1qpv83m6bh67.apps.googleusercontent.com',
    iosClientId:
        '997897806633-5ni700nv2jmak77tmsprsshft6kvn0me.apps.googleusercontent.com',
    iosBundleId: 'com.example.cureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz6d1z4BnINppGC6_5OsxwL570vWSMdbU',
    appId: '1:997897806633:web:356adbbf832dfc6b9acd38',
    messagingSenderId: '997897806633',
    projectId: 'cure-app-ddfd9',
    authDomain: 'cure-app-ddfd9.firebaseapp.com',
    storageBucket: 'cure-app-ddfd9.firebasestorage.app',
    measurementId: 'G-YDV3XKG2CR',
  );
}
